export const data = {
  accounts: [
    {
      id: 1,
      account: "facebook",
      username: "@nathanf",
      avatar: "/images/avatar-facebook.jpg",
      followers: "1987",
      title: "Followers",
      arrow: "up",
      todayText: "12 Today",
    },
    {
      id: 2,
      account: "twitter",
      username: "@nathanf",
      avatar: "/images/avatar-twitter.jpg",
      followers: "1044",
      title: "Followers",
      arrow: "up",
      todayText: "99 Today",
    },
    {
      id: 3,
      account: "instagram",
      username: "@realnathanf",
      avatar: "/images/avatar-instagram.jpg",
      followers: "11k",
      title: "Followers",
      arrow: "up",
      todayText: "1099 Today",
    },
    {
      id: 4,
      account: "youtube",
      username: "Nathan F.",
      avatar: "/images/avatar-youtube.jpg",
      followers: "8239",
      title: "Subscribers",
      arrow: "down",
      todayText: "144 Today",
    },
  ],
  stats: [
    {
      id: 1,
      account: "facebook",
      title: "Page Views",
      amount: "87",
      percent: 3,
      arrow: "up",
    },
    {
      id: 2,
      account: "facebook",
      title: "Likes",
      amount: "52",
      percent: 2,
      arrow: "down",
    },
    {
      id: 3,
      account: "instagram",
      title: "Likes",
      amount: "5462",
      percent: 2257,
      arrow: "up",
    },
    {
      id: 4,
      account: "instagram",
      title: "Profile Views",
      amount: "52k",
      percent: 1375,
      arrow: "up",
    },
    {
      id: 5,
      account: "twitter",
      title: "Retweets",
      amount: "117",
      percent: 303,
      arrow: "up",
    },
    {
      id: 6,
      account: "twitter",
      title: "Likes",
      amount: "507",
      percent: 553,
      arrow: "up",
    },
    {
      id: 7,
      account: "youtube",
      title: "Likes",
      amount: "107",
      percent: 19,
      arrow: "down",
    },
    {
      id: 8,
      account: "youtube",
      title: "Total Views",
      amount: "1407",
      percent: 12,
      arrow: "down",
    },
  ],
};
